config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :royalpasses
  get 'welcome/index'
  devise_for :users
  resources :table1s
  root "welcome#index"
 get 'about' => "table1s#about"
 get 'video' => "royalpasses#video"
  get 'gallery' => "table1s#gallery"
 get 'upsc' => "welcome#upsc"
  get 'trick' => "welcome#trick"
   get 'offers' => "welcome#offers"
   get 'home' => "welcome#open"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/royalpass.rb
class Royalpass < ApplicationRecord
	validates :name, :rp, :pts, :rnk, presence:true
	# belongs_to :table1
end

app/models/table1.rb
class Table1 < ApplicationRecord
	validates :name, :matches, :kd, :hd, :die, presence:true
	# has_many :royalpasses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  # before_action :authenticate_user!
   def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up) do |user_params|

  user_params.permit({ roles: [] }, :email, :password, :password_confirmation)

  end



  devise_parameter_sanitizer.permit(:account_update) do |user_params|

  user_params.permit({ roles: [] }, :email, :password, :password_confirmation, :current_password)

  end
  end

end

app/controllers/royalpasses_controller.rb
class RoyalpassesController < ApplicationController
  before_action :set_royalpass, only: [:show, :edit, :update, :destroy]

  # GET /royalpasses
  # GET /royalpasses.json
  def index
    @royalpasses = Royalpass.all
  end

  # GET /royalpasses/1
  # GET /royalpasses/1.json
  def show
  end
 def video
 end
  # GET /royalpasses/new
  def new
    @royalpass = Royalpass.new
  end

  # GET /royalpasses/1/edit
  def edit
  end

  # POST /royalpasses
  # POST /royalpasses.json
  def create
    @royalpass = Royalpass.new(royalpass_params)

    respond_to do |format|
      if @royalpass.save
        format.html { redirect_to @royalpass, notice: 'Royalpass was successfully created.' }
        format.json { render :show, status: :created, location: @royalpass }
      else
        format.html { render :new }
        format.json { render json: @royalpass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /royalpasses/1
  # PATCH/PUT /royalpasses/1.json
  def update
    respond_to do |format|
      if @royalpass.update(royalpass_params)
        format.html { redirect_to @royalpass, notice: 'Royalpass was successfully updated.' }
        format.json { render :show, status: :ok, location: @royalpass }
      else
        format.html { render :edit }
        format.json { render json: @royalpass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /royalpasses/1
  # DELETE /royalpasses/1.json
  def destroy
    @royalpass.destroy
    respond_to do |format|
      format.html { redirect_to royalpasses_url, notice: 'Royalpass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_royalpass
      @royalpass = Royalpass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def royalpass_params
      params.require(:royalpass).permit(:name, :rp, :pts, :rnk)
    end
end

app/controllers/table1s_controller.rb
class Table1sController < ApplicationController
  before_action :set_table1, only: [:show, :edit, :update, :destroy]

  # GET /table1s
  # GET /table1s.json
  def index
    @table1s = Table1.all
  end

  # GET /table1s/1
  # GET /table1s/1.json
  def show
  end

  # GET /table1s/new
  def new
    @table1 = Table1.new
  end

  # GET /table1s/1/edit
  def edit
  end
 def about
end
  # POST /table1s
  # POST /table1s.json
  def create
    @table1 = Table1.new(table1_params)

    respond_to do |format|
      if @table1.save
        format.html { redirect_to @table1}
        format.json { render :show, status: :created, location: @table1 }
      else
        format.html { render :new }
        format.json { render json: @table1.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /table1s/1
  # PATCH/PUT /table1s/1.json
  def update
    respond_to do |format|
      if @table1.update(table1_params)
        format.html { redirect_to @table1, notice: 'Table1 was successfully updated.' }
        format.json { render :show, status: :ok, location: @table1 }
      else
        format.html { render :edit }
        format.json { render json: @table1.errors, status: :unprocessable_entity }
      end
    end
  end
def gallery
end
  # DELETE /table1s/1
  # DELETE /table1s/1.json
  def destroy
    @table1.destroy
    respond_to do |format|
      format.html { redirect_to table1s_url, notice: 'Table1 was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table1
      @table1 = Table1.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table1_params
      params.require(:table1).permit(:name, :date, :address, :postcode, :matches, :kd, :hd, :die)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def upsc
  end
  def trick
  end
  def offers
  end
  def open
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/royalpasses_helper.rb
module RoyalpassesHelper
end

app/helpers/table1s_helper.rb
module Table1sHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<body>
  <html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
    <head>
      <meta charset="utf-8">
     <!--  <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
      <title> Mobile</title>
      <!-- Bootstrap CSS CDN -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
      <!-- Our Custom CSS -->
      <link rel="stylesheet" href="style.css">
      <!-- Font Awesome JS -->
      <script defer="" src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
      <script defer="" src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    </head>
    <body>
      <div class="wrapper">
        <!-- Sidebar  -->
        <%# if user_signed_in? %>
        <nav id="sidebar" class="">
          <div class="sidebar-header">
            <h3><a href="/">Aiden</a></h3>
          </div>
          <ul class="list-unstyled components">
            <p>Welcome!</p>
            <li class="active">
              <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Royal Pass</a>
              <ul class="collapse list-unstyled" id="homeSubmenu">
                <li>
                  <a href="/royalpasses">Season 11</a>
                </li>
                <li>
                 <!--  <a href="#">Tier</a> -->
                </li>
                <li>
                  <a href="/upsc">Season 12</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="/about">About</a>
            </li>
            <li>
              <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Gallery</a>
              <ul class="collapse list-unstyled" id="pageSubmenu">
                <li>
                  <a href="/gallery">Gallery 1</a>
                </li>
                <li>
                  <a href="#">Page 2</a>
                </li>
                <li>
                  <a href="#">Page 3</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="/table1s">CLAN</a>
            </li>
            <li>
              <a href="trick">Pubg Tricks</a>
            </li>
            <li>
              <a href="offers">Pubg Offers</a>
            </li>
          </ul>
          <ul class="list-unstyled CTAs">
            <li>
              <a href="/admin" class="download">Admin Login</a>
            </li>
            <li>
              <a href="/" class="article">Back to Site</a>
            </li>
          </ul>
          <li>@copyright: iamksr</li>
        </nav>
        <!-- Page Content  -->
        <div id="content">
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <button type="button" id="sidebarCollapse" class="btn btn-info">
                <svg class="svg-inline--fa fa-align-left fa-w-14" aria-hidden="true" data-prefix="fas" data-icon="align-left" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg="">
                  <path fill="currentColor" d="M288 44v40c0 8.837-7.163 16-16 16H16c-8.837 0-16-7.163-16-16V44c0-8.837 7.163-16 16-16h256c8.837 0 16 7.163 16 16zM0 172v40c0 8.837 7.163 16 16 16h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16zm16 312h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm256-200H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16h256c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16z"></path>
                </svg>
                <!-- <i class="fas fa-align-left"></i> -->
                <span>Open Menu</span>
              </button>
              <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <svg class="svg-inline--fa fa-align-justify fa-w-14" aria-hidden="true" data-prefix="fas" data-icon="align-justify" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg="">
                  <path fill="currentColor" d="M0 84V44c0-8.837 7.163-16 16-16h416c8.837 0 16 7.163 16 16v40c0 8.837-7.163 16-16 16H16c-8.837 0-16-7.163-16-16zm16 144h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 256h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0-128h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"></path>
                </svg>
                <!-- <i class="fas fa-align-justify"></i> -->
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav ml-auto">
                  <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/users/edit">Edit Profile</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/video">Watch Videos</a>
                  </li>
                  <!-- <li class="nav-item">
                    <a class="nav-link" href="/users/sign_out">Log Out</a>
                  </li> -->
                </ul>
              </div>
            </div>
          </nav>
          <%#end%>
          <%= yield %>
        </div>
      </div>
    </body>
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <script type="text/javascript">
      $(document).ready(function () {
          $('#sidebarCollapse').on('click', function () {
              $('#sidebar').toggleClass('active');
          });
      });
    </script>
    <style type="text/css">
      /*
      DEMO STYLE
      */
      @import "https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700";
      body {
      font-family: 'Poppins', sans-serif;
      background-color: #7f53ac;
      background-image: linear-gradient(315deg, #7f53ac 0%, #647dee 74%);


      }
      p {
      font-family: 'Poppins', sans-serif;
      font-size: 2.1em;
      font-weight: 500;
      line-height: 1.7em;
      color: #fff;
      }
      h {
      font-family: 'Poppins', sans-serif;
      font-size: 3.1em;
      font-weight: 600;
      background: -webkit-linear-gradient(315deg, #90d5ec 0%, #fc575e 74%);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-color: #9fa4c4;
      }
      h5{
      font-family: 'Poppins', sans-serif;
      font-size: 5.1em;
      font-weight: 600;
      background: linear-gradient(to right, #d01686 0%, #330867 100%);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      }
      h3 {
      font-family: 'Poppins', sans-serif;
      font-size: 2.1em;
      font-weight: 500;
      line-height: 1.7em;
      color: #000;
      }
      p1 {
      font-family: 'Poppins', sans-serif;
      font-size: 2.1em;
      font-weight: 500;
      color: #fff;
      line-height: 1.7em;
      color: #fff;
      }
      a,
      a:hover,
      a:focus {
      color: inherit;
      text-decoration: none;
      transition: all 0.3s;
      }
      .navbar {
      padding: 15px 10px;
      background: #fff;
      border: none;
      border-radius: 0;
      margin-bottom: 40px;
      box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.1);
      }
      .navbar-btn {
      box-shadow: none;
      outline: none !important;
      border: none;
      }
      .line {
      width: 100%;
      height: 1px;
      border-bottom: 1px dashed #ddd;
      margin: 40px 0;
      }
      /* ---------------------------------------------------
      SIDEBAR STYLE
      ----------------------------------------------------- */
      .wrapper {
      display: flex;
      width: 100%;
      align-items: stretch;
      }
      #sidebar {
      min-width: 250px;
      max-width: 250px;
      background: #7386D5;
      color: #fff;
      transition: all 0.3s;
      }
      #sidebar.active {
      margin-left: -250px;
      }
      #sidebar .sidebar-header {
      padding: 20px;
      background: #6d7fcc;
      }
      #sidebar ul.components {
      padding: 20px 0;
      border-bottom: 1px solid #47748b;
      }
      #sidebar ul p {
      color: #fff;
      padding: 10px;
      }
      #sidebar ul li a {
      padding: 10px;
      font-size: 1.1em;
      display: block;
      }
      #sidebar ul li a:hover {
      color: #7386D5;
      background: #fff;
      }
      #sidebar ul li.active>a,
      a[aria-expanded="true"] {
      color: #fff;
      background: #6d7fcc;
      }
      a[data-toggle="collapse"] {
      position: relative;
      }
      .dropdown-toggle::after {
      display: block;
      position: absolute;
      top: 50%;
      right: 20px;
      transform: translateY(-50%);
      }
      ul ul a {
      font-size: 0.9em !important;
      padding-left: 30px !important;
      background: #6d7fcc;
      }
      ul.CTAs {
      padding: 20px;
      }
      ul.CTAs a {
      text-align: center;
      font-size: 0.9em !important;
      display: block;
      border-radius: 5px;
      margin-bottom: 5px;
      }
      a.download {
      background: #fff;
      color: #7386D5;
      }
      a.article,
      a.article:hover {
      background: #6d7fcc !important;
      color: #fff !important;
      }
      /* ---------------------------------------------------
      CONTENT STYLE
      ----------------------------------------------------- */
      #content {
      width: 100%;
      padding: 20px;
      min-height: 100vh;
      transition: all 0.3s;
      }
      /* ---------------------------------------------------
      MEDIAQUERIES
      ----------------------------------------------------- */
      @media (max-width: 768px) {
      #sidebar {
      margin-left: -250px;
      }
      #sidebar.active {
      margin-left: 0;
      }
      #sidebarCollapse span {
      display: none;
      }
      }
    </style>

app/views/royalpasses/_form.html.erb
<%= form_with(model: royalpass, local: true) do |form| %>
  <% if royalpass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(royalpass.errors.count, "error") %> prohibited this royalpass from being saved:</h2>

      <ul>
        <% royalpass.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :royalpass %>
    <%= form.text_field :rp %>
  </div>

  <div class="field">
    <%= form.label :points %>
    <%= form.text_field :pts %>
  </div>

  <div class="field">
    <%= form.label :rnkclan %>
    <%= form.text_field :rnk %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/royalpasses/edit.html.erb
<h1>Editing Royalpass</h1>

<%= render 'form', royalpass: @royalpass %>

<%= link_to 'Show', @royalpass %> |
<%= link_to 'Back', royalpasses_path %>

app/views/royalpasses/index.html.erb
<p id="notice"><%= notice %></p>
<h>GØT々दहशत</h>
<h>Royal Pass S11</h>

<table class="table table-striped">
  <thead>
    <tr>
      <th><h3>Name</h3></th>
      <th><h3>RP</h3></th>

    </tr>
  </thead>

  <tbody>
    <% @royalpasses.each do |royalpass| %>
      <tr>
        <td><p1><%= royalpass.name %></p1></td>
        <td><p1><%= royalpass.rp %></p1></td>
        
        <td><%= link_to 'Show', royalpass, class: "btn btn-danger"%></td>
         <% if current_user.role == "admin" %>
        <td><%= link_to 'Edit', edit_royalpass_path(royalpass) %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/royalpasses/new.html.erb
<h1>New Royalpass</h1>

<%= render 'form', royalpass: @royalpass %>

<%= link_to 'Back', royalpasses_path %>

app/views/royalpasses/show.html.erb
<p id="notice"><%= notice %></p>

<h><strong><%= @royalpass.name %></strong></h>

<p>
  <strong>RP:</strong>
  <%= @royalpass.rp %>
</p>

<p>
  <strong>Points:</strong>
  <%= @royalpass.pts %>
</p>

<p>
  <strong>Rank in Clan:</strong>
  <%= @royalpass.rnk %>
</p>

<%= link_to 'Back', royalpasses_path,class: "btn btn-info"%>

app/views/royalpasses/video.html.erb
<html>
<body>
<h>Royal Pass</h>
<iframe width="380" height="245" src="https://www.youtube.com/embed/NWdK2oKnn2g" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe><br>
<h>Clip-1</h>
<iframe width="380" height="245" src="https://www.youtube.com/embed/cf4i2XwBdrA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe><br>
<h>Clip-2</h><iframe width="380" height="245" src="https://www.youtube.com/embed/AJOF1J8Wnac" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe><br>
<h>Clip-3</h>
<iframe width="380" height="245" src="https://www.youtube.com/embed/mBJsESXyxMg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe><br>
<h>Clip-4</h>
<iframe width="380" height="245" src="https://www.youtube.com/embed/llLru5BNdeo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe><br>
</body>
</html>

app/views/table1s/_form.html.erb
<%= form_with(model: table1, local: true) do |form| %>
  <% if table1.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(table1.errors.count, "error") %> prohibited this table1 from being saved:</h2>

      <ul>
        <% table1.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>



  <div class="field">
    <%= form.label :tier %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :kd %>
    <%= form.text_field :kd %>
  </div>

   <div class="field">
    <%= form.label :hd %>
    <%= form.text_field :hd %>
  </div>
  <div class="field">
    <%= form.label :kill %>
    <%= form.text_field :die %>
  </div>
   <div class="field">
    <%= form.label :matches %>
    <%= form.text_field :matches %>
  </div>




  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/table1s/about.html.erb
<!-- Library Files:- --> 
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">


<!-- BODY:- -->
<body>
<img class="image" src="https://scontent.fdel1-2.fna.fbcdn.net/v/t1.0-9/s960x960/60965412_2660377340856043_5919357952078118912_o.jpg?_nc_cat=101&_nc_ohc=OlOBwY4LFP0AQnutvbyiXEfKE4ar83Bm8olCM0RdJ4fuG_98tzudAx7HQ&_nc_ht=scontent.fdel1-2.fna&oh=14bbd74158c7a225090b7f4ecc56d917&oe=5E712FA7"/>
<h1>This is <strong>Visualize</strong>, a responsive site template designed by Iamksr a Employee of BitternTec in Noida.</h1>

<div class="socialmedia">
<a href="https://twitter.com/tittobhaiya"><i class="fa fa-twitter"></i></a>
<a href="https://www.facebook.com/ImTitto"><i class="fa fa-facebook"></i></a>
<a href="https://www.instagram.com/iamksr/"><i class="fa fa-instagram"></i></a>
<a href="https://www.tumblr.com/blog/tittobhaiya"><i class="fa fa-tumblr"></i></a>
</div>
<h1>This is Our<strong>Info Site</strong>To Check the Statics</h1>

<!-- Cascade Style Sheets -->
<style type="text/css">
  body{
    background: linear-gradient(#E17153, #E58D63, #f1ab53) !important;
    background-repeat: no-repeat; background-size: cover; background-attachment: fixed; text-align: center;
       font-family: Source Sans Pro, sans-serif;font-weight:200; padding-bottom:50px; }
/*IMAGE:-*/
.image {width:  200px;
    height: 200px;
   background: linear-gradient(#F17153, #F58D63, #f1ab53);  border-radius: 50%; margin: 20px auto; padding:5px; border: 1px solid #C7C7D0; margin-top:50px;}
/*H1:-*/

h1 {  font-family: Source Sans Pro, sans-serif; color: #C7C7D0; font-weight:200; margin:10px auto; width:70%; line-height:1.5;}

/*Social Media:-*/
.socialmedia a { background-color:rgba(255, 255, 255, 0.075); text-decoration: none; font-size:16pt; transition:.5s all;
color:#C7C7D0; border:1px solid #C7C7D0; width:50px; height:50px; display: inline-block; padding:10px; border-radius:50% !important ;}

.socialmedia a:hover,strong { color: #FFFFFF; border-color:#FFF; font-weight: 200; }
</style>

app/views/table1s/edit.html.erb
<h1>Editing Table1</h1>

<%= render 'form', table1: @table1 %>

<%= link_to 'Show', @table1 %> |
<%= link_to 'Back', table1s_path %>

app/views/table1s/index.html.erb
<p id="notice"><%= notice %></p>

<h>GØT々दहशत</h>

<table>
  <thead>
    <tr>
      <h3>Name</h3>
      <h3></h3>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @table1s.each do |table1| %>
      <tr>
        <td><p1><%= table1.name %></p1></td>
        <td><%= link_to 'Show', table1,class: "btn btn-primary" %></td>
        <% if current_user.role == "admin" %>
        <td><%= link_to 'Edit', edit_table1_path(table1) %></td>          
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
    

<br>